uploads = []
generated = []

[[outputs]]
id = "VbivRwj_M2jzcSZP9Y7F_"
uri = "file://attached_assets/vpnexus-freekassa.css"
type = "unspecified"
title = "vpnexus-freekassa.css v5 (усиленная специфичность)"

[[outputs]]
id = "0LT9yvCKhE5864rR2XLUT"
uri = "file://attached_assets/vpnexus-logo-light.svg"
type = "image"
title = "Светлый логотип — VPNexus (финал)"

[[outputs]]
id = "_STtL9NNQPoDjzYJelf65"
uri = "file://attached_assets/vpnexus-logo-dark.svg"
type = "image"
title = "Тёмный логотип — VPNexus (финал)"

[[outputs]]
id = "lZOwc6UcwvohMPcrGQRaZ"
uri = "file://attached_assets/vpnexus-logo-light.jpg"
type = "image"
title = "Светлый логотип — JPG"

[[outputs]]
id = "12y-WTp6uHbu7vBcYQs6i"
uri = "file://attached_assets/vpnexus-logo-dark.jpg"
type = "image"
title = "Тёмный логотип — JPG"
