import { integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export interface ProvisionLogLine {
  ts: number;
  text: string;
  level: "info" | "step" | "success" | "error";
}

/**
 * Persistent store for SSH provisioning jobs.
 *
 * Logs are written incrementally to the `logs` JSONB column so they survive
 * server restarts and container redeploys. The in-memory EventEmitter is still
 * used to fan-out live SSE streams to connected clients; the DB is the source
 * of truth for reconnecting clients or late-joiners after a restart.
 */
export const provisioningJobsTable = pgTable("provisioning_jobs", {
  /** UUID generated by the provisioner. */
  id: text("id").primaryKey(),
  /** Job lifecycle state. */
  status: text("status", { enum: ["running", "done", "error"] }).notNull().default("running"),
  /** Ordered log lines accumulated during the job. */
  logs: jsonb("logs").$type<ProvisionLogLine[]>().notNull().default([]),
  /** Set once the node is registered in the DB. */
  nodeId: integer("node_id"),
  /** Set when the job ends in error. */
  errorMessage: text("error_message"),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
});

export type ProvisioningJob = typeof provisioningJobsTable.$inferSelect;
export type InsertProvisioningJob = typeof provisioningJobsTable.$inferInsert;
